// data.js - Nampo GoGo Premium Global Data Dictionary with Subcategories for Delivery UI

window.NampoGoGoData = {
  // Translations supporting KR, EN, CH, JP
  translations: {
    kr: {
      appName: "Nampo GoGo",
      dashboard: "대시보드",
      explore: "맛집 탐색",
      travelLog: "여행 로그",
      profile: "내 정보",
      tagline: "남포동 스마트 로컬여행 플랫폼",
      pleaseLogin: "로그인 후 QR 인증과 여행 로그를 기록해 보세요.",
      welcomeUser: "남포동에 오신 것을 환영합니다!",
      roleVisitor: "관광객 (손님)",
      roleMerchant: "제휴 사업자 (상인)",
      roleAdmin: "시스템 관리자 (어드민)",
      updateBtn: "업데이트 내역",
      updateTitle: "최근 업데이트 소식",
      
      // Intro translation keys
      introTouristTitle: "여행객 전용",
      introTouristDesc: "제휴 매장 검색, 길찾기, QR 스탬프 로그 모드",
      introTouristBtn: "접속하기 ➔",
      introMerchantTitle: "사업자 전용",
      introMerchantDesc: "매장 등록, 다중 업로드 가이드, 메뉴/결제 관리",
      introMerchantBtn: "가입 및 관리 ➔",

      // Core Categories
      allCategories: "전체 카테고리",
      catMassage: "뷰티 & 마사지",
      catFood: "남포 맛집",
      catCafe: "감성 카페",
      catShopping: "쇼핑 & 패션",
      catSightseeing: "관광 & 야경",
      
      // Delivery UI Subcategories
      subPork: "국밥/한식",
      subSeafood: "해산물/회",
      subPizza: "피자/양식",
      subKorean: "전통한식",
      subChinese: "중식/요리",
      subJapanese: "일식/돈까스",
      subMassage: "마사지/뷰티",
      subCafe: "디저트/카페",

      // Actions & Labels
      benefitTitle: "🎁 제휴 관광객 전용 단독 혜택",
      getDirection: "도보 길찾기 📍",
      distance: "현재 거리",
      alreadyStamped: "인증 완료 ✓",
      scanBtnText: "매장 QR 스탬프 스캔",
      reviewTitle: "방문자 한줄 평 및 리뷰",
      noReviews: "아직 작성된 리뷰가 없습니다.",
      ratingLabel: "평가 점수",
      reviewInputPlaceholder: "매장 이용 후 한 줄 리뷰를 남겨주세요 (체크인 완료 고객 전용)",
      reviewBtn: "리뷰 등록 완료",
      reviewAuthError: "⚠️ 이 매장의 QR 인증(체크인)을 마친 고객만 리뷰를 남길 수 있습니다.",
      
      // Travel Log page
      logTitle: "나의 여행 로그 카드",
      logDesc: "QR 인증으로 수집된 나만의 남포동 여행 코스 리포트입니다.",
      logCount: "방문한 매장 수",
      emptyLog: "아직 방문 인증된 매장이 없습니다. 제휴 매장을 방문하고 스탬프를 적립해 보세요!",
      snsExport: "SNS 공유용 카드 생성 📸",
      snsCopyText: "공유 텍스트 복사",
      snsDownloadImg: "스토리 카드 다운로드",
      snsSuccess: "📋 인스타그램 공유용 텍스트가 클립보드에 복사되었습니다! 스토리 카드와 함께 공유해 보세요.",
      memoLabel: "나만의 한줄 여행 메모 기록",
      memoPlaceholder: "이 매장에서 어떤 추억이 있었나요? 메모를 입력하세요.",
      memoSaveBtn: "메모 저장",
      memoSavedSuccess: "💾 여행 메모가 안전하게 저장되었습니다!",

      // Auth & Profile
      loginTitle: "3초 초간단 가입 & 로그인",
      loginDesc: "아이디와 비밀번호만 입력하면 즉시 가입 및 이용이 가능합니다.",
      joinTypeVisitor: "관광객(손님)으로 가입",
      joinTypeMerchant: "사업자(상인)로 가입",
      usernamePlaceholder: "아이디(닉네임) 입력",
      passwordPlaceholder: "비밀번호 입력",
      passwordConfirmPlaceholder: "비밀번호 확인 입력",
      authBtn: "로그인 / 가입 완료",
      logoutBtn: "로그아웃",

      // Merchant Dashboard
      merchantTitle: "내 매장 관리 대시보드",
      merchantDesc: "오늘 방문자 수와 스탬프 발급 건수를 체크하고 정보를 편집하세요.",
      visitorToday: "오늘 방문자 수",
      visitorTotal: "누적 방문자 수",
      qrStampsIssued: "QR 인증 횟수",
      reviewCount: "등록된 리뷰 수",
      editStoreInfo: "매장 상세 정보 수정",
      saveStoreSuccess: "💾 매장 정보 및 다중 미디어가 성공적으로 업데이트되었습니다!",
      
      // Admin Dashboard
      adminTitle: "Nampo GoGo 통합 어드민",
      adminDesc: "새 매장 정보 등록, 업데이트 공지 관리 및 전체 리뷰 모니터링을 수행합니다.",
      addStoreBtn: "➕ 신규 제휴 매장 등록",
      storeNameLabel: "매장명",
      storeCategoryLabel: "카테고리",
      storeImageLabel: "대표 이미지 URL",
      storeBenefitLabel: "관광객 혜택 내용",
      storePriceLabel: "가격 정보",
      isPartnerLabel: "Nampo GoGo 공식 제휴 등록 여부",
      addStoreSuccess: "🎉 신규 제휴 매장이 정상적으로 등록되었습니다!",
      writeNoticeBtn: "📢 공지사항 및 업데이트 추가",
      noticePlaceholder: "공지할 업데이트 내용을 입력하세요."
    },
    en: {
      appName: "Nampo GoGo",
      dashboard: "Dashboard",
      explore: "Explore",
      travelLog: "Travel Log",
      profile: "My Page",
      tagline: "Nampodong Smart Local Tour Platform",
      pleaseLogin: "Please login to record your QR scans and travel logs.",
      welcomeUser: "Welcome to Nampodong, Busan!",
      roleVisitor: "Tourist",
      roleMerchant: "Merchant Owner",
      roleAdmin: "Administrator",
      updateBtn: "Update Logs",
      updateTitle: "Recent Platform Updates",
      
      // Intro translation keys
      introTouristTitle: "For Tourists",
      introTouristDesc: "Explore partners, get route guides, and scan stamps.",
      introTouristBtn: "Enter ➔",
      introMerchantTitle: "For Merchants",
      introMerchantDesc: "Register store, upload media guidelines, manage menus.",
      introMerchantBtn: "Manage ➔",

      allCategories: "All Categories",
      catMassage: "Beauty & Massage",
      catFood: "Nampo Eats",
      catCafe: "Cafes",
      catShopping: "Shopping",
      catSightseeing: "Night View",
      
      subPork: "Soup/Korean",
      subSeafood: "Seafood/Raw",
      subPizza: "Pizza/Pasta",
      subKorean: "Traditional",
      subChinese: "Chinese",
      subJapanese: "Sushi/Katsu",
      subMassage: "Massage",
      subCafe: "Dessert/Cafe",

      benefitTitle: "🎁 Tourist Exclusive Benefit",
      getDirection: "Get Route 📍",
      distance: "Distance",
      alreadyStamped: "Stamped ✓",
      scanBtnText: "Scan QR Check-in",
      reviewTitle: "Verified User Reviews",
      noReviews: "No reviews written yet.",
      ratingLabel: "Score",
      reviewInputPlaceholder: "Leave your one-line review here (Stamped customers only)",
      reviewBtn: "Post Review",
      reviewAuthError: "⚠️ Only users who completed QR check-in here can write a review.",
      
      logTitle: "My Travel Log Card",
      logDesc: "Your unique Nampodong route report collected via QR scans.",
      logCount: "Visited Shops",
      emptyLog: "No visited shops recorded yet. Start scan QR stamps!",
      snsExport: "Generate SNS Card 📸",
      snsCopyText: "Copy Text",
      snsDownloadImg: "Download Story Card",
      snsSuccess: "📋 Text copied to clipboard! Share it on Instagram stories.",
      memoLabel: "My Travel Memo",
      memoPlaceholder: "What memories did you have here? Enter your memo.",
      memoSaveBtn: "Save Memo",
      memoSavedSuccess: "💾 Travel memo saved safely!",

      loginTitle: "3-Sec Quick Sign-up & Login",
      loginDesc: "Just enter ID and Password to start immediately.",
      joinTypeVisitor: "Sign up as Tourist",
      joinTypeMerchant: "Sign up as Business Owner",
      usernamePlaceholder: "Enter Username",
      passwordPlaceholder: "Enter Password",
      passwordConfirmPlaceholder: "Confirm Password",
      authBtn: "Complete Login",
      logoutBtn: "Logout",

      merchantTitle: "Store Control Dashboard",
      merchantDesc: "Track today's visits, stamp records, and update details.",
      visitorToday: "Visits Today",
      visitorTotal: "Accumulated Visits",
      qrStampsIssued: "QR Stamps",
      reviewCount: "Reviews Count",
      editStoreInfo: "Edit Store Details",
      saveStoreSuccess: "💾 Store updates and media successfully applied!",
      
      adminTitle: "Nampo GoGo Admin Panel",
      adminDesc: "Register new partner shops, manage notice updates, and reviews.",
      addStoreBtn: "➕ Register New Partner Store",
      storeNameLabel: "Store Name",
      storeCategoryLabel: "Category",
      storeImageLabel: "Cover Image URL",
      storeBenefitLabel: "Tourist Exclusive Benefit",
      storePriceLabel: "Price Info",
      isPartnerLabel: "Register as Official Nampo GoGo Partner",
      addStoreSuccess: "🎉 New partner store registered successfully!",
      writeNoticeBtn: "📢 Post Notice / Platform Update",
      noticePlaceholder: "Enter notice contents."
    },
    ch: {
      appName: "Nampo GoGo",
      dashboard: "仪表盘",
      explore: "探店发现",
      travelLog: "旅游日志",
      profile: "个人信息",
      tagline: "南浦洞智能旅游平台",
      pleaseLogin: "请先登录以记录您的QR扫码与足迹日志。",
      welcomeUser: "欢迎来到釜山南浦洞！",
      roleVisitor: "观光游客",
      roleMerchant: "合作商户",
      roleAdmin: "系统管理员",
      updateBtn: "更新日志",
      updateTitle: "平台最新更新",
      
      // Intro translation keys
      introTouristTitle: "游客专用",
      introTouristDesc: "查找合作商家、查看步行导航、扫码打卡足迹。",
      introTouristBtn: "进入 ➔",
      introMerchantTitle: "商户专用",
      introMerchantDesc: "录入店铺信息、上传规定证照照片与商品菜单。",
      introMerchantBtn: "注册管理 ➔",

      allCategories: "全部类别",
      catMassage: "美容按摩",
      catFood: "南浦美食",
      catCafe: "精品咖啡",
      catShopping: "购物时尚",
      catSightseeing: "观光夜景",
      
      subPork: "汤饭/韩餐",
      subSeafood: "海鲜刺身",
      subPizza: "批萨西餐",
      subKorean: "传统韩餐",
      subChinese: "中华料理",
      subJapanese: "日式猪排",
      subMassage: "美容按摩",
      subCafe: "甜点咖啡",

      benefitTitle: "🎁 游客专属合作优惠",
      getDirection: "步行导航 📍",
      distance: "当前距离",
      alreadyStamped: "认证成功 ✓",
      scanBtnText: "扫描商户QR码",
      reviewTitle: "真实游客评价",
      noReviews: "暂无评价。",
      ratingLabel: "评分",
      reviewInputPlaceholder: "留下您的一句话评价（仅限完成扫码认证的顾客）",
      reviewBtn: "发布评价",
      reviewAuthError: "⚠️ 只有在此商户完成过QR认证扫码的顾客才能撰写评价。",
      
      logTitle: "我的旅行卡片",
      logDesc: "通过QR认证收集的南浦洞特色旅游足迹报告。",
      logCount: "已访问商户数",
      emptyLog: "暂无访问记录。快去拜访合作商家并收集印章吧！",
      snsExport: "生成分享卡片 📸",
      snsCopyText: "复制分享文案",
      snsDownloadImg: "下载卡片图片",
      snsSuccess: "📋 分享文案已复制到剪贴板！可与卡片图片一起分享至社交平台。",
      memoLabel: "我的旅行随手记",
      memoPlaceholder: "在这里留下了什么回忆？输入您的旅行笔记。",
      memoSaveBtn: "保存笔记",
      memoSavedSuccess: "💾 笔记已安全保存！",

      loginTitle: "3秒极速注册与登录",
      loginDesc: "只需输入账号和密码即可立即使用平台。",
      joinTypeVisitor: "以游客身份注册",
      joinTypeMerchant: "以商户身份注册",
      usernamePlaceholder: "输入账号",
      passwordPlaceholder: "输入密码",
      passwordConfirmPlaceholder: "再次输入密码确认",
      authBtn: "完成登录 / 注册",
      logoutBtn: "登出账号",

      merchantTitle: "店铺管理面板",
      merchantDesc: "查看今日客流、扫码印章并发包新商户动态。",
      visitorToday: "今日访客",
      visitorTotal: "累计访客",
      qrStampsIssued: "QR认证印章",
      reviewCount: "已收到评价",
      editStoreInfo: "修改店铺详情",
      saveStoreSuccess: "💾 店铺信息与上传的多媒体已更新成功！",
      
      adminTitle: "南浦GoGo超级管理台",
      adminDesc: "添加新商户、发布更新通知并监控全局评价信息。",
      addStoreBtn: "➕ 录入全新合作商户",
      storeNameLabel: "店铺名称",
      storeCategoryLabel: "主营门类",
      storeImageLabel: "门面图片链接",
      storeBenefitLabel: "游客优惠内容",
      storePriceLabel: "招牌价格信息",
      isPartnerLabel: "设为南浦GoGo官方星级合作商户",
      addStoreSuccess: "🎉 合作店铺录入成功！",
      writeNoticeBtn: "📢 发布系统公告或版本迭代",
      noticePlaceholder: "输入要发布的信息内容。"
    },
    jp: {
      appName: "Nampo GoGo",
      dashboard: "ダッシュボード",
      explore: "店舗検索",
      travelLog: "トラベルログ",
      profile: "マイページ",
      tagline: "南浦洞スマートローカル旅行プラットフォーム",
      pleaseLogin: "ログインしてQR認証とトラベルログを記録しましょう。",
      welcomeUser: "釜山・南浦洞へようこそ！",
      roleVisitor: "観光客",
      roleMerchant: "提携加盟店",
      roleAdmin: "管理者",
      updateBtn: "更新ログ",
      updateTitle: "最近の更新情報",
      
      // Intro translation keys
      introTouristTitle: "旅行者専用",
      introTouristDesc: "加盟店検索、ルートナビ、QRスタンプ記録機能。",
      introTouristBtn: "アクセス ➔",
      introMerchantTitle: "事業者専用",
      introMerchantDesc: "店舗の登録、コンテンツ規格チェック、メニュー管理。",
      introMerchantBtn: "管理ページ ➔",

      allCategories: "全カテゴリー",
      catMassage: "エステ & 마ッサージ",
      catFood: "南浦グルメ",
      catCafe: "カフェ",
      catShopping: "ショッピング",
      catSightseeing: "観光スポット",
      
      subPork: "クッパ/韓国食",
      subSeafood: "海鮮/刺身",
      subPizza: "ピザ/洋食",
      subKorean: "伝統韓国食",
      subChinese: "中華料理",
      subJapanese: "和食/トンカツ",
      subMassage: "エステマッサージ",
      subCafe: "デザートカフェ",

      benefitTitle: "🎁 観光客提携限定特典",
      getDirection: "徒歩ルート案内 📍",
      distance: "現在位置からの距離",
      alreadyStamped: "認証完了 ✓",
      scanBtnText: "店舗QRコード読み取り",
      reviewTitle: "訪問者レビュー",
      noReviews: "レビューはまだありません。",
      ratingLabel: "評価スコア",
      reviewInputPlaceholder: "一行レビューを残してください（チェックイン完了顧客専用）",
      reviewBtn: "レビューを登録する",
      reviewAuthError: "⚠️ 店舗でQRチェックインを完了したお客様のみレビューを書くことができます。",
      
      logTitle: "マイ・トラベル・ログカード",
      logDesc: "QRチェックインで収集された南浦洞での足跡ルートレポート。",
      logCount: "Grid",
      emptyLog: "訪れた加盟店がまだありません。提携店舗に行ってスタンプを集めましょう！",
      snsExport: "SNS共有用カード作成 📸",
      snsCopyText: "共有用文言をコピー",
      snsDownloadImg: "ストーリーカードを保存",
      snsSuccess: "📋 インスタグラム共有用のテキストがクリップボードにコピーされました！画像と一緒に共有してください。",
      memoLabel: "旅行の一行メモ",
      memoPlaceholder: "ここでどんな思い出がありましたか？メモを入力してください。",
      memoSaveBtn: "メモを保存",
      memoSavedSuccess: "💾 メモが正常に保存されました！",

      loginTitle: "3秒で簡単登録 & ログイン",
      loginDesc: "ユーザー名とパスワードのみで即座に登録してご利用いただけます。",
      joinTypeVisitor: "観光客として会員登録",
      joinTypeMerchant: "加盟店主として会員登録",
      usernamePlaceholder: "ユーザー名を入力",
      passwordPlaceholder: "パスワードを入力",
      passwordConfirmPlaceholder: "確認用パスワードを入力",
      authBtn: "ログイン / 登録完了",
      logoutBtn: "ログアウト",

      merchantTitle: "店舗管理ダッシュボード",
      merchantDesc: "今日の訪問者数、スタンプログを確認し、店舗情報を修正します。",
      visitorToday: "今日の訪問者数",
      visitorTotal: "累計訪問者数",
      qrStampsIssued: "QR認証数",
      reviewCount: "登録レビュー数",
      editStoreInfo: "店舗詳細情報を編集",
      saveStoreSuccess: "💾 店舗情報と追加メディアが正常にアップデートされました！",
      
      adminTitle: "Nampo GoGo 統合アドミン",
      adminDesc: "新規提携加盟店の登録、お知らせ更新、全体レビューの管理を行います。",
      addStoreBtn: "➕ 新規提携店を登録する",
      storeNameLabel: "店舗名",
      storeCategoryLabel: "カテゴリー",
      storeImageLabel: "カバー画像URL",
      storeBenefitLabel: "観光客特典内容",
      storePriceLabel: "価格情報",
      isPartnerLabel: "公式提携加盟店として登録",
      addStoreSuccess: "🎉 新規店舗が正常に登録されました！",
      writeNoticeBtn: "📢 加盟店お知らせ・機能更新を追加",
      noticePlaceholder: "お知らせする内容を入力してください。"
    }
  },

  // 8 default partner stores
  partners: [
    {
      id: "partner_klounge",
      name: {
        kr: "K-Lounge 스포츠 아로마 테라피",
        en: "K-Lounge Sports & Aroma Therapy",
        ch: "K-Lounge 运动精油指压理疗",
        jp: "K-Lounge スポーツアロマセラピー"
      },
      category: "massage",
      subCategory: "massage",
      isPartner: true,
      image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=600&q=80",
      gallery: [],
      rating: 4.9,
      scores: { hygiene: 5.0, taste: 4.8, service: 5.0, cleanliness: 4.8 },
      posX: 129.034789,
      posY: 35.097489,
      mapLinkNaver: "https://map.naver.com/v5/directions/14363294,35.097489,내위치,,/14363310,35.098222,K-Lounge,,/walk",
      mapLinkGoogle: "https://www.google.com/maps/dir/?api=1&origin=35.097489,129.034789&destination=35.098222,129.035789&travelmode=walking",
      distanceValue: "70m",
      address: {
        kr: "부산 중구 구덕로 48 3층 (남포역 1번출구 도보 1분)",
        en: "3F, 48 Gudeok-ro, Jung-gu, Busan (1-min walk from Nampo exit 1)",
        ch: "釜山中区九德路48号3楼 (南浦站1号出口步行1分钟)",
        jp: "釜山中区九徳路48 3階 (南浦駅1번出口から徒歩1分)"
      },
      phone: "+82-51-248-1234",
      hours: "10:00 - 02:00",
      priceList: [
        { name: { kr: "스포츠 집중 테라피 (60분)", en: "Sports Deep Therapy (60m)", ch: "运动集中理疗 (60分)", jp: "スポーツ集中コース (60分)" }, price: "60,000 KRW" },
        { name: { kr: "아로마 바디 가이드 힐링 (90분)", en: "Aroma Body Healing (90m)", ch: "精油全身舒缓 (90分)", jp: "アロマボディコース (90分)" }, price: "90,000 KRW" }
      ],
      menuForeign: {
        en: "Full menu card in English, Japanese and Chinese provided at reception.",
        ch: "接待处提供英、日、中三语完整菜单手册。",
        jp: "受付にて英語・中国語・日本語の各種メニュー完備。"
      },
      benefits: {
        kr: "Nampo GoGo 회원 전용: 코스 10% 추가 즉시 할인 및 허브티 서비스",
        en: "Exclusive: Extra 10% instant discount + complimentary herbal tea.",
        ch: "专属福利: 全身理疗项目立享9折优惠，加赠特调草本养生茶。",
        jp: "会員特典: 全コース10%即時割引 & ハーブティーサービス"
      },
      seoDescription: "Busan Nampodong Best Premium massage shop K-Lounge. Sports and Aroma massage courses.",
      seoKeywords: "Nampodong massage, Busan massage, K-Lounge massage",
      reviews: [
        { username: "TravelerKim", rating: 5.0, content: { kr: "도보 여행에 뭉친 피로가 완전히 풀렸습니다. 강추합니다!", en: "Perfect deep pressure. Friendly staff!", ch: "手法非常专业，旅行中的疲劳一扫而空，强烈推荐！", jp: "とても気持ちよかったです。スタッフがとても親切でした。" } }
      ],
      parking: "유"
    },
    {
      id: "partner_pork_grand",
      name: {
        kr: "할매 원조 부산 돼지국밥",
        en: "Halmae Original Busan Pork Soup",
        ch: "老奶奶釜山猪肉汤饭",
        jp: "ハルメ元祖釜山デジクッパ"
      },
      category: "food",
      subCategory: "pork",
      isPartner: true,
      image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80",
      gallery: [],
      rating: 4.8,
      scores: { hygiene: 4.7, taste: 5.0, service: 4.6, cleanliness: 4.5 },
      posX: 129.035123,
      posY: 35.09789,
      mapLinkNaver: "https://map.naver.com/v5/directions/14363294,35.097489,내위치,,/14363400,35.098300,원조돼지국밥,,/walk",
      mapLinkGoogle: "https://www.google.com/maps/dir/?api=1&origin=35.097489,129.034789&destination=35.098300,129.036000&travelmode=walking",
      distanceValue: "180m",
      address: {
        kr: "부산 중구 남포길 12 (광복로 먹자골목 인근)",
        en: "12 Nampo-gil, Jung-gu, Busan (Gwangbok-ro Food Street)",
        ch: "釜山中区南浦路12号 (光复路美食街附近)",
        jp: "釜山中区南浦路12 (光復路グルメ通り付近)"
      },
      phone: "+82-51-245-7890",
      hours: "24 Hours (연중무휴)",
      priceList: [
        { name: { kr: "따로 돼지국밥", en: "Pork Soup (Rice separate)", ch: "招牌猪肉汤饭", jp: "デジクッパ (スープとご飯別)" }, price: "9,000 KRW" },
        { name: { kr: "모듬 수육 (소)", en: "Assorted Sliced Pork (S)", ch: "精选白切肉 (小)", jp: "ゆで豚肉スライス (小)" }, price: "28,000 KRW" }
      ],
      menuForeign: {
        en: "Eng/Ch/Jp picture menu card is fully available.",
        ch: "提供图文并茂的英中日菜单。",
        jp: "英語・中国語・日本語の写真付きメニューあり。"
      },
      benefits: {
        kr: "국밥 주문 시 수제 맛보기 순대 1인 2점 무료 제공",
        en: "Order soup and get 2 free slices of handmade sausage per person.",
        ch: "凡点汤饭，即赠送手工血肠（每人2块）。",
        jp: "クッパご注文で、自家製スン데お一人様2切れサービス"
      },
      seoDescription: "Traditional Busan Pork Rice Soup restaurant near Gwangbok-ro, Busan.",
      seoKeywords: "Busan pork soup, Nampodong food, pork rice soup",
      reviews: [],
      parking: "무"
    },
    {
      id: "partner_jagalchi_fish",
      name: {
        kr: "자갈치 제일 랍스터 & 회센터",
        en: "Jagalchi No.1 Lobster & Raw Fish Center",
        ch: "札嘎其第一龙虾刺身海鲜中心",
        jp: "チャガルチ第一ロブスター&刺身センター"
      },
      category: "food",
      subCategory: "seafood",
      isPartner: true,
      image: "https://images.unsplash.com/photo-1534400298786-1df5024da1a1?auto=format&fit=crop&w=600&q=80",
      gallery: [],
      rating: 4.7,
      scores: { hygiene: 4.8, taste: 4.9, service: 4.5, cleanliness: 4.7 },
      posX: 129.034123,
      posY: 35.096123,
      mapLinkNaver: "https://map.naver.com/v5/directions/14363294,35.097489,내위치,,/14362800,35.095800,자갈치회센터,,/walk",
      mapLinkGoogle: "https://www.google.com/maps/dir/?api=1&origin=35.097489,129.034789&destination=35.095800,129.033000&travelmode=walking",
      distanceValue: "290m",
      address: {
        kr: "부산 중구 자갈치해안로 52 2층 35호",
        en: "No. 35, 2F, 52 Jagalchihaean-ro, Jung-gu, Busan",
        ch: "釜山中区札嘎其海岸路52号2楼35号",
        jp: "釜山中区チャガルチ海岸路52 2階35号"
      },
      phone: "+82-51-246-8899",
      hours: "11:00 - 23:00 (화요일 휴무)",
      priceList: [
        { name: { kr: "생선회 모듬 패키지 (2인)", en: "Premium Raw Fish Assortment (2p)", ch: "精选生鱼片拼盘 (2人份)", jp: "刺身盛り合わせ (2人前)" }, price: "60,000 KRW" },
        { name: { kr: "랍스터 코스 정식 (1인)", en: "Lobster Course Set (1p)", ch: "奢华龙虾套餐 (单人)", jp: "ロブスターコース (1人前)" }, price: "80,000 KRW" }
      ],
      menuForeign: {
        en: "Multilingual staff and menu options are fully supported.",
        ch: "店内配有中文翻译职员及中英日对照图文菜单。",
        jp: "外国人向けセットメニュー及び外国語対応スタッフ常駐。"
      },
      benefits: {
        kr: "모듬회 이상 주문시 매운탕 무료 제공 및 소주 1병 서비스",
        en: "Get a free spicy fish soup and 1 bottle of Soju with raw fish platter.",
        ch: "点生鱼片拼盘，免费送鲜辣鱼汤及韩国烧酒1瓶。",
        jp: "刺身ご注文でメウンタン(辛い魚スープ) & 焼酎1本サービス"
      },
      seoDescription: "Fresh Seafood and Lobster restaurant at Jagalchi Fish Market in Busan.",
      seoKeywords: "Jagalchi fish market, lobster raw fish, Busan seafood",
      reviews: [],
      parking: "유"
    },
    {
      id: "partner_pizza_napo",
      name: {
        kr: "광복로 화덕 피자 마스터",
        en: "Gwangbok-ro Wood-fired Pizza Master",
        ch: "光复路窑烤意式披萨大师",
        jp: "光復路窯焼きピザマスター"
      },
      category: "food",
      subCategory: "pizza",
      isPartner: false,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80",
      gallery: [],
      rating: 4.6,
      scores: { hygiene: 4.6, taste: 4.7, service: 4.5, cleanliness: 4.6 },
      posX: 129.036123,
      posY: 35.098456,
      mapLinkNaver: "https://map.naver.com/v5/directions/14363294,35.097489,내위치,,/14363800,35.099100,피자마스터,,/walk",
      mapLinkGoogle: "https://www.google.com/maps/dir/?api=1&origin=35.097489,129.034789&destination=35.099100,129.037100&travelmode=walking",
      distanceValue: "220m",
      address: {
        kr: "부산 중구 광복중앙로 8-2 2층",
        en: "2F, 8-2 Gwangbokjungang-ro, Jung-gu, Busan",
        ch: "釜山中区光复中央路8-2号2楼",
        jp: "釜山中区光復中央路8-2 2階"
      },
      phone: "+82-51-255-0987",
      hours: "11:30 - 21:30",
      priceList: [
        { name: { kr: "마르게리타 화덕 피자", en: "Margherita Wood-Fired Pizza", ch: "经典玛格丽特窑烤披萨", jp: "マルゲリータピザ" }, price: "18,900 KRW" },
        { name: { kr: "감베로니 스파게티", en: "Gamberoni Pasta", ch: "意式鲜虾意面", jp: "海老パスタ" }, price: "15,500 KRW" }
      ],
      menuForeign: {
        en: "English names written on normal menu layout.",
        ch: "菜单配有英文和中文注释。",
        jp: "メニューに英語表記あり。"
      },
      benefits: {
        kr: "일반 제휴 신청 매장: 탄산음료 1캔 무료 증정",
        en: "Get 1 free soda can with your main dish.",
        ch: "点主食即免费赠送碳酸饮料1罐。",
        jp: "メイン料理ご注文で炭酸ドリンク1缶サービス"
      },
      seoDescription: "Delicious wood-fired pizza and pasta restaurant at Gwangbok-ro.",
      seoKeywords: "Nampodong pizza, Gwangbokro pasta, wood-fired pizza",
      reviews: [],
      parking: "무"
    },
    {
      id: "partner_cafe_gwangbok",
      name: {
        kr: "카페 광복동 아틀리에",
        en: "Cafe Gwangbokdong Atelier",
        ch: "光复洞艺术工坊咖啡厅",
        jp: "カフェ光復洞アトリエ"
      },
      category: "cafe",
      subCategory: "cafe",
      isPartner: true,
      image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80",
      gallery: [],
      rating: 4.8,
      scores: { hygiene: 4.9, taste: 4.8, service: 4.7, cleanliness: 4.8 },
      posX: 129.034567,
      posY: 35.099123,
      mapLinkNaver: "https://map.naver.com/v5/directions/14363294,35.097489,내위치,,/14363220,35.099600,카페광복동,,/walk",
      mapLinkGoogle: "https://www.google.com/maps/dir/?api=1&origin=35.097489,129.034789&destination=35.099600,129.033500&travelmode=walking",
      distanceValue: "150m",
      address: {
        kr: "부산 중구 광복로 67-1 3층",
        en: "3F, 67-1 Gwangbok-ro, Jung-gu, Busan",
        ch: "釜山中区光复路67-1号3楼",
        jp: "釜山中区光復路67-1 3階"
      },
      phone: "+82-51-246-3300",
      hours: "11:00 - 22:30",
      priceList: [
        { name: { kr: "수제 아인슈페너", en: "Signature Einspanner", ch: "手工维也纳咖啡", jp: "自家製アインシュペナー" }, price: "6,500 KRW" },
        { name: { kr: "전통 딸기 와플", en: "Classic Strawberry Waffle", ch: "草莓华夫饼", jp: "いちごワッフル" }, price: "12,000 KRW" }
      ],
      menuForeign: {
        en: "Eng/Jp display labels next to items.",
        ch: "餐牌注有英文和日文说明。",
        jp: "英語・日本語の並記あり。"
      },
      benefits: {
        kr: "음료 주문시 수제 아몬드 피낭시에 테이블당 1개 무료 제공",
        en: "Get 1 complimentary almond financier cookie per table with drinks.",
        ch: "凡点咖啡饮品，即赠送手工杏仁费南雪蛋糕（每桌1个）。",
        jp: "ドリンクご注文でフィナンシェお一つサービス (1テーブルあたり)"
      },
      seoDescription: "Beautiful interior roof cafe at Gwangbokro shopping street, Busan.",
      seoKeywords: "Gwangbokro cafe, Nampodong dessert, Einspanner",
      reviews: [],
      parking: "무"
    }
  ],

  // Default notices
  updateHistory: [
    { date: "2026-07-07", content: "배달 어플리케이션(배민/요기요) 스타일의 카테고리/매장 리스트 디자인 개편 완료! 🛵" },
    { date: "2026-07-06", content: "사업자 제휴 승인 조건 검증 및 음식점 메뉴(결제수단, 주차여부) 등록 폼 셋업 완료!" },
    { date: "2026-07-05", content: "모바일 최적화 다국어 구글/네이버 도보 길찾기 지도 정밀 맵 매핑 개통!" }
  ]
};
