// Generated by build script. Do not edit manually.
class BuildInfo {
  static const String versionName = 'RELEASE-001-I3';
  static const String commitHash = 'f08c38e';
  static const String buildTime = '2026-07-31 07:57:59 KST';

  static String get fullDisplay => '$versionName ($commitHash) / $buildTime';
}
