services:
  backend:
    build:
      context: ./backend
    container_name: nampo_gogo_backend
    ports:
      - "18080:18080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app

  db:
    image: postgres:16
    container_name: nampo_gogo_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
